version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - app-network
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge