version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge